### ISSUE TITLE
Missing system message variable

### ISSUE THREAD

**Issue by HoiDam** [mathyousee/power-platform-chatGPT#2]
Hi mathyousee. Would like to know what variable should i put in here. thanks bro~
![image](https://github.com/mathyousee/power-platform-chatGPT/assets/66233626/d9e08a3b-131e-4a6a-9121-e1471a6cf892)

**Comment by mathyousee** [comment]
Hi @HoiDam, sorry for the delay in response. The variable you should use here is Global.SystemMessage. This variable is initialized in the **Conversation Start** topic if you want to adjust it.

**Comment by HoiDam** [comment]
Cheers
