### ISSUE TITLE
Can't deploy ZIP as Solution in Power Apps

### ISSUE THREAD

**Issue by juangon** [mathyousee/power-platform-chatGPT#3]
Hi! Your project looks pretty good and complete. I wanted to take a look by deploying the ZIP within PowerApps, but I couldn't. Can you point me to some documentation about how to deploy the ZIP file in SolutionFileHistory?

Thanks!

**Comment by mathyousee** [comment]
Hi @juangon thanks for the compliment. The ZIP files in that folder are Solution files, which can be uploaded by going to the Power Platform maker portal (https://make.powerapps.com), selecting Solutions in the left navigation, then choosing import. 

The complete steps to import can be found here, though there's a lot of extraneous detail not relevant to the sample solution in this repo. https://learn.microsoft.com/en-us/power-apps/maker/data-platform/import-update-export-solutions

**Comment by mathyousee** [comment]
Here's a couple of screenshot in case it helps. Note: you may need to use the "More..." navigation item if Solutions isn't visible in the list.

![image](https://github.com/mathyousee/power-platform-chatGPT/assets/418063/3af365b8-442e-4db5-ab65-2cd96806dc29)

![image](https://github.com/mathyousee/power-platform-chatGPT/assets/418063/741c7164-8be4-40fc-aa28-74e67ba0a4cc)
